name: ath_mobile
description: Athena Skin Diagnosis
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  http: ^0.13.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.4
  auto_route: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.0

flutter:
  uses-material-design: true
